name: Build and Publish Docker Image

on:
  push:
    branches:
      - main # execute GitHub Actions when a code it pushed to main

env:
  REGISTRY: ghcr.io
  #  IMAGE_NAME: ${{ github.repository }}
#  IMAGE_NAME: $(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g')

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. check up codes in repository
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Log in GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Set image name
      - name: Set image name
        id: set-image-name
        run: |
          IMAGE_NAME=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g')
          echo "::set-output name=image_name::$IMAGE_NAME"

      # 4. Extract metadata (tags, labels) for Docker
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ steps.set-image-name.outputs.image_name }}

      # 5. Build Docker image
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # 6. Generate artifact attestation
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ steps.set-image-name.outputs.image_name }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
